### ISSUE TITLE
video tutorial plz? :)

### ISSUE THREAD

**Issue by MaxMohammadi** [dabit3/full-stack-web3#1]

**Comment by dabit3** [comment]
Yes! Working on this next.

**Comment by OfficialOzioma** [comment]
Please can you notify me when the **video tutorial i**s ready?
Email: **dikep15@gmail.com**

**Comment by dabit3** [comment]
Video tutorial is now available here https://glass.xyz/v/zsadHIYLeEtkiJMWcAXA84lDQKhSPvf6_mK3z4l-_2U=

cc @OfficialOzioma @MaxMohammadi
